### ISSUE TITLE
permimp error (Error in levels(block) <- seq_len(nlevels(block)) :  attempt to set an attribute on NULL)

### ISSUE THREAD

**Issue by avannucci** [ddebeer/permimp#1]
I get the following error when I try to run the permimp function following party::cforest -> seq_len(nlevels(block)) :  attempt to set an attribute on NULL)

# code for conditional random forest with party package
crf <- party::cforest(Y ~ ., data = df_rf, controls = cforest_unbiased(ntree = 10000, mtry = 7))

# code for permutation importance
pi <- permimp::permimp(crf, conditional = T, progressBar = F, asParty=T)

versions: 
* R v. 4.1.2
* party package v. 1.3.10
* permimp package v. 1.0.2

Can you help me understand how to resolve this error? Dataframe attached to see if you can replicate the error. All predictor variables are factors except for: CGH_SUM_SWITCH, crea_early_min, crea_dev_window, and starts_with("APQ_"). Outcome response is Y

[df_rf.csv](https://github.com/ddebeer/permimp/files/9224108/df_rf.csv)
.

**Comment by ddebeer** [comment]
[Resolved by the user.](https://github.com/ddebeer/permimp/issues/2)
